name: 'Setup node'
description: 'Install requeired dependency.'
inputs:
  id:
    required: true
  keepalive:
    required: true
  frps_host:
    required: true
  frps_remote_port:
    required: true
  openvpn_ca_crt:
    required: true
  openvpn_ta_key:
    required: true
  openvpn_password:
    required: true
runs:
  using: "composite"
  steps: 
    # - name: Setup Docker
    #   uses: docker/setup-buildx-action@v2.0.0

    - name: Install frpc
      shell: bash
      run: |
        sudo export NODE_NAME=${{ inputs.keepalive }}
        sudo export FRPS_HOST=${{ inputs.frps_host }}
        sudo export FRPS_REMOTE_PORT=${{ inputs.frps_remote_port }}
        sudo export OPENVPN_CA_CRT=${{ inputs.openvpn_ca_crt }}
        sudo export OPENVPN_TA_KEY=${{ inputs.openvpn_ta_key }}
        sudo export OPENVPN_PASSWORD=${{ inputs.openvpn_password }}
        sudo bash ./setup.sh
          
    - name: Don't kill instace
      shell: bash
      run: sleep ${{ inputs.keepalive }}
