name: slave2
on: 
  repository_dispatch:
    types: [slave2]
jobs:
  slave2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Add SSH pub key
        run: |
          mkdir /home/runner/.ssh
          echo "${{ secrets.SSH_KEY_FOR_DEBUG }}" >> /home/runner/.ssh/authorized_keys
          chmod 600 /home/runner/.ssh/authorized_keys

      - name: Setup Node
        uses: ./.github/cust-actions/setup-node
        with:
          id: "slave2"
          frps_host: ${{ secrets.FRPS_HOST }}
          frps_remote_port: 7102
          keepalive: ${{ github.event.client_payload.keepalive }}
